services:
  btcn_web:
    build:
      context: .
    image: web_btcn_image
    ports:
      - 8003:8000
    env_file:
      - src.env
    depends_on:
      - db
    restart: unless-stopped
    command: ["python", "BTCN_price.py"]




  db:
    image: timescale/timescaledb:latest-pg17
    hostname: db
    ports:
      - "5632:5432"
    restart: unless-stopped
    env_file:
     - db.env #При удалении контейнера чтобы дефольная бд постгресс заново инициализировалась
     #Эти переменные (POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD) работают только при первом запуске, когда в каталоге данных (/var/lib/postgresql/data) ещё нет инициализированной базы.
    volumes:
      - pg_data:/var/lib/postgresql/data


volumes:
  pg_data: