services:
  btcn_web:
    build:
      context: .
    image: web_btcn_image
    ports:
      - 8003:8000
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    command: >
      sh -c "cd src && uvicorn fast:app --host 0.0.0.0 --port 8000"




  db:
    image: timescale/timescaledb:latest-pg17
    hostname: db
    ports:
      - "5632:5432"
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: